closes #21
jelmervdl/empty-train pull request #27
Opened 2022-09-08 15:27 UTC by ales-t

2022-09-08 16:28 UTC, jelmervdl commented
It looks like it is breaking when used with monolingual filters (e.g. _deescape-special-chars_). Probably because that also wraps the command in a `col.py` call.

Error:
```
/bin/sh: -c: line 0: syntax error near unexpected token `;'
/bin/sh: -c: line 0: `; /Users/jelmer/Workspace/statmt/empty-train/col.py 1 ./deescape-special-chars.perl'
```

2022-09-09 15:13 UTC, ales-t commented
@jelmervdl It's not about the monolingual filters specifically, I think. It's just that the filter doesn't specify any variables which is an edge case I didn't handle. You can check the updated version.

2022-09-10 11:54 UTC, jelmervdl requested changes
Looks good to me! Just need to remove the left-over `print(command)` debug code :)

2022-09-10 11:54 UTC, jelmervdl commented on main.py
> +
```suggestion
```

2022-09-10 11:55 UTC, jelmervdl approved these changes

2022-09-10 11:56 UTC, merged